### ISSUE TITLE
Remove the cfg file from download for better mod manger support

### ISSUE THREAD

**Issue by jacobmix** [KlutzyBubbles/lc-better-emotes#1]
Please remove the .cfg file from download to not reset configs every update if people use mod managers.
.cfg file should get created automatically if it doesn't exist or updated if new configs get created i believe.
This goes for the original mod by Sligili as well, but he doesn't have his GitHub linked.

**Comment by KlutzyBubbles** [comment]
I just downloaded 1.1.3 and the config file is in the zip. However i will look into removing the config from the zip anyway as it was also an annoyance when i update the mod and the keybinds reset.

**Comment by KlutzyBubbles** [comment]
Fixed in v1.0.6
