### ISSUE TITLE
Emotes and wheel don't work

### ISSUE THREAD

**Issue by DeathIdk** [KlutzyBubbles/lc-better-emotes#10]
Pressing V or the other emote keys (besides 1 and 2) doesn't do anything, friend of mine had the same issue. Tried to rebind the keys but didn't work either.

**Comment by senolem** [comment]
same, tried deleting every config file, deleted the mod, reinstalled, restarted the game and still not working :(

**Comment by RyanHipkiss** [comment]
yeah got the same issue here, seems something has broke

**Comment by AwesomeEli13** [comment]
I am having the same issue

**Comment by KlutzyBubbles** [comment]
Curious to whether or not LC API is installed alongside? I have heard a lot of issues stemming from the new LC API update but dont have a computer atm to check

**Comment by KlutzyBubbles** [comment]
Found a possible temporary solution. It seems like the InputUtils mod got updated recently, and the 0.4.3 update stops the mods keybinds from activating. Downgrading InputUtils to 0.4.2 should fix this issue while i see if its possible for this to be fixed soon.

**Comment by KlutzyBubbles** [comment]
I believe v1.3.1 should fix this issue, i will leave the issue open for another day just incase people still have issues.
