### ISSUE TITLE
I can't move when i have MoreEmotes

### ISSUE THREAD

**Issue by r1chiks** [KlutzyBubbles/lc-better-emotes#12]
I can't move when i download this mod(MoreEmotes),can u help me fix that

**Comment by KlutzyBubbles** [comment]
> I can't move when i download this mod(MoreEmotes),can u help me fix that

Can you send me the thunderstore/r2modman profile code or a list of other mods you have installed?

I have just tried installing the mod and it works fine

**Comment by KlutzyBubbles** [comment]
Lack of response and re reading the issue they say MoreEmotes instead of BetterEmotes. Shouldnt be any issues.
