### ISSUE TITLE
Conflict with LCVR

### ISSUE THREAD

**Issue by Nathan22211** [KlutzyBubbles/lc-better-emotes#16]
not tested it personally but it seems that the mod dev did find a conflict with better emotes and his mod (quoted from his compatibility sheet) 

"BetterEmotes and LCVR are interfering with each other when updating the player controller animator"

**Comment by KlutzyBubbles** [comment]
> not tested it personally but it seems that the mod dev did find a conflict with better emotes and his mod (quoted from his compatibility sheet)
> 
> "BetterEmotes and LCVR are interfering with each other when updating the player controller animator"

This is a known issue with MoreEmotes (the mod this one is heavily reliant on) and this will be an issue until MoreEmotes fixes it or when i learn how to animate things, whichever comes first (probably MoreEmotes updating).

For now disabling or uninstalling the mod should cause no issues, because i havent added the sign emote yet BetterEmotes is still client side and anyone can choose to have it installed or not.

**Comment by KlutzyBubbles** [comment]
> there's a toggle in the config for more emote if my memory serves me right that fixes it, and it seems other emote mods don't have this issue from looking at the spreadsheet

I am still working on updating the mod (code / progress can be found https://github.com/KlutzyBubbles/lc-better-emotes/tree/moreemotes-1.3.1).

When that is complete and working, i would imagine the VR incompatibilities will also sort themselves out, but if they dont, then i can work on it.

**Comment by KlutzyBubbles** [comment]
> there's a toggle in the config for more emote if my memory serves me right that fixes it, and it seems other emote mods don't have this issue from looking at the spreadsheet

I have recently published [v1.4.0](https://github.com/KlutzyBubbles/lc-better-emotes/releases/tag/v1.4.0), not sure if it still has the incompatibilities.

I dont believe much has changed so it probably still doesn't work well but i dont have the setup to test it

**Comment by Nelots** [comment]
I just loaded the game up in VR and I can confirm the mods are still incompatible.

>For now disabling or uninstalling the mod should cause no issues, because i havent added the sign emote yet BetterEmotes is still client side and anyone can choose to have it installed or not.

On another note, now that you've added the sign emote, does that mean the mod is no longer client-sided and can't be removed if one person wants to use VR?

**Comment by KlutzyBubbles** [comment]
> On another note, now that you've added the sign emote, does that mean the mod is no longer client-sided and can't be removed if one person wants to use VR?

I am not entirely sure, i will add that to some things i should test. But the implementation is the same as MoreEmotes (i havent had time to properly alter the integration methods just yet) so if it happens in MoreEmotes it will more than likely happen with BetterEmotes

**Comment by KlutzyBubbles** [comment]
> I just loaded the game up in VR and I can confirm the mods are still incompatible.
> 
> > For now disabling or uninstalling the mod should cause no issues, because i havent added the sign emote yet BetterEmotes is still client side and anyone can choose to have it installed or not.
> 
> On another note, now that you've added the sign emote, does that mean the mod is no longer client-sided and can't be removed if one person wants to use VR?



> there's a toggle in the config for more emote if my memory serves me right that fixes it, and it seems other emote mods don't have this issue from looking at the spreadsheet

I have recently posted v1.4.1 which should add support for LCVR. It should disable emotes for anyone using VR, but still let VR players view non VR players emotes.

Please note that you will get console errors if not all other people in the lobby have BetterEmotes also.
