### ISSUE TITLE
Point Emote no longer works

### ISSUE THREAD

**Issue by yNaht** [KlutzyBubbles/lc-better-emotes#2]
Seems like once you download and use this mod the point emote is replaced by a second dance emote.

**Comment by KlutzyBubbles** [comment]
I am unable to recreate this on a fresh profile. Can you check / send an image of your key binds in game?

**Comment by KlutzyBubbles** [comment]
An update has been pushed to update to the most recent MoreEmotes features. Perhaps v1.2.0 has fixed this issue?

**Comment by yNaht** [comment]
It could be because im also using the TooManyEmotes mod as well. It claims it can work with your MoreEmotes mod so i guess it does not work with this one. sorry for the trouble, if any thing maybe just put that BetterEmotes is not compatible with other emote mods but  MoreEmotes is?

**Comment by KlutzyBubbles** [comment]
> It could be because im also using the TooManyEmotes mod as well. It claims it can work with your MoreEmotes mod so i guess it does not work with this one. sorry for the trouble, if any thing maybe just put that BetterEmotes is not compatible with other emote mods but MoreEmotes is?

Ok, i have also confirmed that. It seems the TooManyEmotes mod has implemented a compatibility check for MoreEmotes but not BetterEmotes :(

I am currently looking into a compatibility update

**Comment by KlutzyBubbles** [comment]
I have updated it to have some support for TooManyEmotes HOWEVER, there are some issues still present (one most notably the point keybind doesnt work but the point in emote wheel does work)

And i for the life of me cannot figure it out, its the exact same code being run. so i have decided to push what i have and give it a break.
