### ISSUE TITLE
Incompatible with TooManyEmotes

### ISSUE THREAD

**Issue by ajsglist** [KlutzyBubbles/lc-better-emotes#24]
BetterEmotes 1.4.2 is broken for clients (all with same mod list/identical configs) with TooManyEmotes.  For reference, MoreEmotes 1.3.3 does not reproduce this bug.

Clients loading into the lobby report their camera bugging out and frenetically bobbing uncontrollably.  Included is the relevant log info
[BetterEmotes_TooManyEmotes_critical_conflict.txt](https://github.com/KlutzyBubbles/lc-better-emotes/files/14094623/BetterEmotes_TooManyEmotes_critical_conflict.txt)

Thanks!

**Comment by KlutzyBubbles** [comment]
> BetterEmotes 1.4.2 is broken for clients (all with same mod list/identical configs) with TooManyEmotes. For reference, MoreEmotes 1.3.3 does not reproduce this bug.
> 
> Clients loading into the lobby report their camera bugging out and frenetically bobbing uncontrollably. Included is the relevant log info [BetterEmotes_TooManyEmotes_critical_conflict.txt](https://github.com/KlutzyBubbles/lc-better-emotes/files/14094623/BetterEmotes_TooManyEmotes_critical_conflict.txt)
> 
> Thanks!

I have just created a profile with `BetterEmotes 1.4.2` and `TooManyEmotes 1.8.5` and both client and host can start and view their own and other peoples emotes on both mods. Which makes me believe there is another mod causing the issues.

I will need your profile code to import into my mod manager to test further.

**Comment by ajsglist** [comment]
Thank you for the quick response, and apologies for the confusion.  At the time of playing, we were using TooManyEmotes 1.8.3.  We don't use the mod manager to ensure everyone is using an identical pack with identical configs.  Here is as much of the information from the time of error as I can think to include, if there's something else that would help just let me know.

For simplicity, I have attached the mod list (as a text file) + configs from both mods at the time the client error was observed.

My group is asleep, so I don't have any means to test anything from outside the host's perspective (or check if TME 1.8.5 may have resolved the issue) at the moment, sorry :(
[TME_BE_conflict_mod_list.txt](https://github.com/KlutzyBubbles/lc-better-emotes/files/14095620/TME_BE_conflict_mod_list.txt)
[configs.zip](https://github.com/KlutzyBubbles/lc-better-emotes/files/14095637/configs.zip)

**Comment by KlutzyBubbles** [comment]
> Thank you for the quick response, and apologies for the confusion. At the time of playing, we were using TooManyEmotes 1.8.3. We don't use the mod manager to ensure everyone is using an identical pack with identical configs. Here is as much of the information from the time of error as I can think to include, if there's something else that would help just let me know.
> 
> For simplicity, I have attached the mod list (as a text file) + configs from both mods at the time the client error was observed.
> 
> My group is asleep, so I don't have any means to test anything from outside the host's perspective (or check if TME 1.8.5 may have resolved the issue) at the moment, sorry :( [TME_BE_conflict_mod_list.txt](https://github.com/KlutzyBubbles/lc-better-emotes/files/14095620/TME_BE_conflict_mod_list.txt) [configs.zip](https://github.com/KlutzyBubbles/lc-better-emotes/files/14095637/configs.zip)

For future reference, i would suggest using a mod manager.

![image](https://github.com/KlutzyBubbles/lc-better-emotes/assets/8754707/ac80ac74-5dc3-4592-aa5f-5c237f46de8f)

The mod managers have a feature that allows you to export a profile as a code which includes all mods, their respective versions and the configs all in a string that looks like `018d59be-5069-5514-9d08-c69232e67181` instead of sharing zip files and copy pasting files

I understand that not everyone wants to install mod managers (although r2modman has a portable version that doesn't even need to be installed) so for your group it may not work but for looking at issues like this it saves a lot of time on my part. And a lot of mod authors just wont look at an issue if you dont have the profile code.

This message had nothing to do with the issue, i am still going to install the mods and see if i can replicate it. Just trying my best to show that mod managers aren't that bad and are usually easier than the alternative (manual installs)

**Comment by KlutzyBubbles** [comment]
> Thank you for the quick response, and apologies for the confusion. At the time of playing, we were using TooManyEmotes 1.8.3. We don't use the mod manager to ensure everyone is using an identical pack with identical configs. Here is as much of the information from the time of error as I can think to include, if there's something else that would help just let me know.
> 
> For simplicity, I have attached the mod list (as a text file) + configs from both mods at the time the client error was observed.
> 
> My group is asleep, so I don't have any means to test anything from outside the host's perspective (or check if TME 1.8.5 may have resolved the issue) at the moment, sorry :( [TME_BE_conflict_mod_list.txt](https://github.com/KlutzyBubbles/lc-better-emotes/files/14095620/TME_BE_conflict_mod_list.txt) [configs.zip](https://github.com/KlutzyBubbles/lc-better-emotes/files/14095637/configs.zip)

By process of disabling mods one by one and launching 2 instances in lan. I believe the culprit is `Entity378-Motion_Tracker_V2-1.0.2`. Disabling this mod makes the issue go away. 

Because the Motion Tracker causes errors in both emote mods, i would consider it to be an issue with it instead of the emote mods. However i will leave this issue open until it is fixed on their end. 

If they dont want to fix it then i will look into fixing it in this mod, but for the time being i will leave it as is

**Comment by ajsglist** [comment]
Thank you!!! And apologies again for the difficulty, I'm sorry for using up your time debugging this.  I'm extremely grateful for the help.

I did not know I could launch multiple Lethal Company sessions to test via LAN.  But I have reproduced the issue exactly as you have detailed.  I will report the underlying conflict to the motion tracker dev.

Thanks again

**Comment by jakeb072001** [comment]
Exact same issue with ModelReplacementAPI as well

**Comment by KlutzyBubbles** [comment]
> Exact same issue with ModelReplacementAPI as well
> 
> Edit: I should also note that this issue only occurs with version 1.4.0 of this mod and later, 1.3.4 works fine

I have been unable to replicate this issue with the ModelReplacementAPI (i have tried some models). Would you be able to narrow it down by disabling mods until you dont have the issue, or send me the profile code and i might be able to look at it (but sending me the code will take a while as i am busy for the next week).

**Comment by jakeb072001** [comment]
Yeah I can do that, it may take a little bit as I have a lot of mods but I'll find what mod is causing it.

**Comment by jakeb072001** [comment]
Alright, seems to also be Immersive Visor causing the issue.

Only seems to cause the issue with ModelReplacementAPI, Immersive Visor and this mod installed at the same, removing any one of those three mods fixes the issue.

**Comment by KlutzyBubbles** [comment]
> Alright, seems to also be Immersive Visor causing the issue.
> 
> Only seems to cause the issue with ModelReplacementAPI, Immersive Visor and this mod installed at the same, removing any one of those three mods fixes the issue.

Using the following mods

`BepInEx-BepInExPack-5.4.2100
Rune580-LethalCompany_InputUtils-0.6.1
Ozone-Runtime_Netcode_Patcher-0.2.5
BunyaPineTree-ModelReplacementAPI-2.3.6
Woecust-Immersive_Visor-0.2.1
KlutzyBubbles-BetterEmotes-1.4.2`

I was still unable to replicate the issue. This was tested on LAN. Are there other mods that you have loaded?

**Comment by jakeb072001** [comment]
Dammit, my Immersive Visor was out of date.
Issue is fixed now, sorry for any time this may have wasted

**Comment by Entity378** [comment]
> > Thank you for the quick response, and apologies for the confusion. At the time of playing, we were using TooManyEmotes 1.8.3. We don't use the mod manager to ensure everyone is using an identical pack with identical configs. Here is as much of the information from the time of error as I can think to include, if there's something else that would help just let me know.
> > For simplicity, I have attached the mod list (as a text file) + configs from both mods at the time the client error was observed.
> > My group is asleep, so I don't have any means to test anything from outside the host's perspective (or check if TME 1.8.5 may have resolved the issue) at the moment, sorry :( [TME_BE_conflict_mod_list.txt](https://github.com/KlutzyBubbles/lc-better-emotes/files/14095620/TME_BE_conflict_mod_list.txt) [configs.zip](https://github.com/KlutzyBubbles/lc-better-emotes/files/14095637/configs.zip)
> 
> By process of disabling mods one by one and launching 2 instances in lan. I believe the culprit is `Entity378-Motion_Tracker_V2-1.0.2`. Disabling this mod makes the issue go away.
> 
> Because the Motion Tracker causes errors in both emote mods, i would consider it to be an issue with it instead of the emote mods. However i will leave this issue open until it is fixed on their end.
> 
> If they dont want to fix it then i will look into fixing it in this mod, but for the time being i will leave it as is

While trying to solve a config syncing problem for my mod I made a huge mistake. Now that I have fixed the config syncing this problem should also be resolved.

**Comment by CptPakundo** [comment]
I actually have the same issue, but with a HUGE (and fully updated) modpack:
018d6bdf-5f0a-71ba-9ffd-913cfadfa813

This is a VR supported modlist. VR players can play perfectly fine (with self emoting disabled, as needed), but non-VR players cannot move at all if both of these mods are enabled.
Disabling one of the two (doesn't matter which) solves the problem.

**Comment by KlutzyBubbles** [comment]
> I actually have the same issue, but with a HUGE (and fully updated) modpack:
> 018d6bdf-5f0a-71ba-9ffd-913cfadfa813
> 
> This is a VR supported modlist. VR players can play perfectly fine (with self emoting disabled, as needed), but non-VR players cannot move at all if both of these mods are enabled.
> Disabling one of the two (doesn't matter which) solves the problem.

I won't be able to test for at least 3 days. I do however have a beta branch (named polishing) in this GitHub.

If you know how to traverse GitHub, you can switch to that branch, download and zip the Mod package folder and then import it to your mod manager. It may already fix the issue but again I can't test for at least 3 days sorry.

**Comment by CptPakundo** [comment]
> > I actually have the same issue, but with a HUGE (and fully updated) modpack:
> > 018d6bdf-5f0a-71ba-9ffd-913cfadfa813
> > This is a VR supported modlist. VR players can play perfectly fine (with self emoting disabled, as needed), but non-VR players cannot move at all if both of these mods are enabled.
> > Disabling one of the two (doesn't matter which) solves the problem.
> 
> I won't be able to test for at least 3 days. I do however have a beta branch (named polishing) in this GitHub.
> 
> If you know how to traverse GitHub, you can switch to that branch, download and zip the Mod package folder and then import it to your mod manager. It may already fix the issue but again I can't test for at least 3 days sorry.

Well, I tried the polishing branch and what do you know - I could move again! Thanks!
