### ISSUE TITLE
VR Support issue

### ISSUE THREAD

**Issue by AstralEsther** [KlutzyBubbles/lc-better-emotes#25]
There is an issue with the VR support as it causes things like heavy items or the Mini Terminal from Advanced Company to show up wrong on screen for non VR players , is there a version I can download that has no VR support so I no longer will have this issue? I just want my friends to hit the griddy

**Comment by KlutzyBubbles** [comment]
> There is an issue with the VR support as it causes things like heavy items or the Mini Terminal from Advanced Company to show up wrong on screen for non VR players , is there a version I can download that has no VR support so I no longer will have this issue? I just want my friends to hit the griddy

Do you have a profile code i can use to see what mods you have installed.

I tested the VR compatibility for many hours before releasing and played many hours with friends in VR with the update with no problems on either end. Which makes me believe there is another mod causing the issue. (Or it is just an incompatibility with another mod that i just dont use, there are so many these days its hard to keep track)

**Comment by KlutzyBubbles** [comment]
> Thank you so much for answering , here it is : 018d6537-0ee7-6ed5-a521-3aded2a2d6b1 I'd not say it's incompatible, it's just that a functionality of a certain mod works wrong with how the portable terminal spawns, the issue was gone after I disabled BetterEmotes
> 
> if it's something that can't be helped , what is the version that happened before the VR Support? Just so I can download this one instead
> 
> Then again, it's very much possible I should have contacted the folks behind Advanced Company instead and if that was the case,sorry for wasting the time

1.4.0 is the one before VR support https://github.com/KlutzyBubbles/lc-better-emotes/releases However advanced company will most likely still have issues, you might have to go back to 1.3.x for now without the 2 new emotes

But i do have some good news, a beta i am currently testing fixes these issues for a lot of mods including Advanced Company, (that will be out next week hopefully).

Also for more information about what actually went wrong, the 1.4 update changed the folder structure a bit which meant any other mods trying to hook into better emotes started getting errors (this happened with TooManyEmotes as well but it was fixed on their end.)

I will create an issue with AdvancedCompany and they may be able to fix it before i push the 1.4.3 update.

**Comment by KlutzyBubbles** [comment]
This should be fixed in [v1.4.3](https://github.com/KlutzyBubbles/lc-better-emotes/releases/tag/v1.4.3). Feel free to let me know if you have any issues

**Comment by AstralEsther** [comment]
Hi! Sorry I couldn't respond earlier but that's amazing ! Thank you so much for everything !
