### ISSUE TITLE
[Issue] v50 kitchen knife animation not working

### ISSUE THREAD

**Issue by CoolLKKPS** [KlutzyBubbles/lc-better-emotes#29]
**Install Method**
R2Modman

**BetterEmotes Version**
1.4.5

**Lethal Company Version**
v50

**Describe the bug**
kitchen knife animation not working

**To Reproduce**
u just need to test by urself

**Expected behavior**
u just need to test by urself

**Logs**
u just need to test by urself

**Screenshots / Videos**
u just need to test by urself

**Additional notes**
u just need to test by urself

**Comment by CoolLKKPS** [comment]
remove some false issues report

**Comment by KlutzyBubbles** [comment]
What is the 'kitchen knife animation'. This mod has

Middle_Finger
Clap
Shy
Griddy
Twerk
Salute
Prisyadka
Sign

**Comment by CoolLKKPS** [comment]
no not that mean, when u swing the knife u will see

**Comment by suwonsarara** [comment]
> What is the 'kitchen knife animation'. This mod has
> 
> Middle_Finger Clap Shy Griddy Twerk Salute Prisyadka Sign

In V50, when you use the knife in the game, your perspective should show the knife swinging up and down. I installed More_emotes but found out the author abandoned compatibility. Later, I tried Better_emotes, and indeed, the issue persisted. There were sound effects, and it could damage enemies, but there was no motion in my own perspective. It remained still.

**Comment by KlutzyBubbles** [comment]
I see, i havent actually tried the new update, and i wont be able to get around to testing and fixing this issue for a few days at least.

From the limited information at hand it sounds like its a new animation attached to the player body. This mod replaces that player body and because it hasnt been updated any new animations wont be there. The big unfortunate thing about this is i never got rebuilding the animations working so i dont even know if i can fix it.

but i will try.

**Comment by RatserX** [comment]
So, any progress on this?

**Comment by KlutzyBubbles** [comment]
> So, any progress on this?

No :( i was hoping sligili would come back. At the moment i don't have the knowledge or time to fix this.

If anyone can (or anyone knows anyone who can) remake the animations in a unity project then i am more than happy to give credit and merge it in with this project.

I just dont have access to the animations sligili created, only the ripped files which i cant get working in any project.

This is all the information i have gotten from sligili a while back

> try [AssetRipper](https://github.com/AssetRipper/AssetRipper) to extract the scavenger model and all animations/animators.
> These are the full model constraints
> Use evaisa's template project (unity 2022.3.9f1), that will setup most stuff but u'll still need to import the IK package and copy every constraint config from the game into the metarig.
> For the asset bundles i think i just followed this tutorial https://thirteenov.ciihuy.com/how-to-create-asset-bundles-in-unity-by-script/
![image](https://github.com/KlutzyBubbles/lc-better-emotes/assets/8754707/a7183c14-d7d8-44a3-9017-10745460c9b8)
> Add a rig component to the parent (Rig 1)
> The weights should be all at 1 but i was previewing an animation
> These are for the first person hands
![image](https://github.com/KlutzyBubbles/lc-better-emotes/assets/8754707/9c4eb77a-7bcd-47da-bec7-89dc6f7c2487)

**Comment by KlutzyBubbles** [comment]
Should be fixed in v1.5.0
