### ISSUE TITLE
Shift + Enter breaks sign emote

### ISSUE THREAD

**Issue by allanjales** [KlutzyBubbles/lc-better-emotes#33]
**Install Method**
Thunderstore App

**BetterEmotes Version**
v1.5.0

**Lethal Company Version**
v50

---

When I press Shift + Enter to break line while I am writing a sign, typing breaks. I can not continue typing and my cursor disapear.

**To Reproduce**
1. Type `0` to start writing a sign
2. Type anything like `line1`
3. Press `Shift + Enter` to break line
4. See error. Notice you can not write beyond this point anymore.

**Expected behavior**
Obviously, I expected to continue typing after line break.

**Logs**
No useful log is produced

**Additional notes**
I have tested with only the BetterEmotes installed.

**Comment by KlutzyBubbles** [comment]
This looks to be a side effect of the new assetbundles, I am still waiting for the person who made them to share the unity project and am currently unable to fix this.

If i have still not gotten the unity project or rebuilt assetbundles to fix this, i will most likely try find someone to help re-repackage the assetbundles to fix this but for now its just a waiting game.

The only other solution for now would be to downgrade to v1.4.5, it is still compatible with v50 you will just lose the knife animation.

**Comment by allanjales** [comment]
I just wanted to add one more thing to my report. 

I noticed that I can indeed continue typing after pressing Shift+Enter.

I realized that the text area is just deselected, and to continue typing, I need to **click on it with the cursor**.

**Comment by DarthLilo** [comment]
Going to look into this as well

**Comment by DarthLilo** [comment]
FIxed, will be out on the next update

**Comment by KlutzyBubbles** [comment]
Closing as IIRC it should be fixed now, feel free to comment or raise a new issue if the problem comes back.
