### ISSUE TITLE
V55 (beta) Company Cruiser gets broken by this mod

### ISSUE THREAD

**Issue by EchoLWS999** [KlutzyBubbles/lc-better-emotes#34]
Letting you know way ahead of time that the Company Cruiser seat gets placed way too high when this mod is enabled, rendering it completely useless.

**Comment by KlutzyBubbles** [comment]
> Letting you know way ahead of time that the Company Cruiser seat gets placed way too high when this mod is enabled, rendering it completely useless.

Will look into this after the unity project PR. Sorry i didn't respond earlier, my github notifications haven't been working.

**Comment by EchoLWS999** [comment]
Perfectly okay, just wanted to make sure you were aware on very early notice

**Comment by KlutzyBubbles** [comment]
Should be fixed in v1.5.2
