### ISSUE TITLE
Incompatibility with PiggysVarietyMod

### ISSUE THREAD

**Issue by Jawzper** [KlutzyBubbles/lc-better-emotes#37]
When both mods are installed the console is spammed with the below error and animations from both mods break. This issue was not present when I was still using More_Emotes in v50, but now that v56 is out it was time to upgrade.

I would really like to use both mods, naturally having a nice package of preset emotes and being able to shoot things with a revolver are both very important aspects of working for The Company. 

If some kind of compatibility fix or workaround can be added it would be greatly appreciated! 

`[Error  : Unity Log] TypeLoadException: Failure has occurred while loading a type.
Stack trace:
PiggyVarietyMod.Patches.PlayerControllerBPatch.Update_Postfix (GameNetcodeStuff.PlayerControllerB __instance, UnityEngine.Animator& ___playerBodyAnimator) (at <8a6490cfe7ff4ebe84eb996f6efa6f97>:IL_0037)
(wrapper dynamic-method) GameNetcodeStuff.PlayerControllerB.DMD<GameNetcodeStuff.PlayerControllerB::Update>(GameNetcodeStuff.PlayerControllerB)`

This can be replicated by installing both BetterEmotes and PiggysVarietyMod and then loading any save file.

**Comment by KlutzyBubbles** [comment]
> When both mods are installed the console is spammed with the below error and animations from both mods break. This issue was not present when I was still using More_Emotes in v50, but now that v56 is out it was time to upgrade.
> 
> I would really like to use both mods, naturally having a nice package of preset emotes and being able to shoot things with a revolver are both very important aspects of working for The Company.
> 
> If some kind of compatibility fix or workaround can be added it would be greatly appreciated!
> 
> `[Error : Unity Log] TypeLoadException: Failure has occurred while loading a type. Stack trace: PiggyVarietyMod.Patches.PlayerControllerBPatch.Update_Postfix (GameNetcodeStuff.PlayerControllerB __instance, UnityEngine.Animator& ___playerBodyAnimator) (at <8a6490cfe7ff4ebe84eb996f6efa6f97>:IL_0037) (wrapper dynamic-method) GameNetcodeStuff.PlayerControllerB.DMD<GameNetcodeStuff.PlayerControllerB::Update>(GameNetcodeStuff.PlayerControllerB)`
> 
> This can be replicated by installing both BetterEmotes and PiggysVarietyMod and then loading any save file.

This looks like an error from PiggyVarietyMod which i have no control over. If you have other errors that are coming from this mod then I can look into them.

However this should be redirected to the PiggyVarietyMod for now.
