### ISSUE TITLE
Can't shake v61 new monster when BetterEmotes is installed

### ISSUE THREAD

**Issue by AboveFire** [KlutzyBubbles/lc-better-emotes#42]
**Install Method**
Thunderstore App

**BetterEmotes Version**
v1.5.3

**Lethal Company Version**
E.g. v61
---
**Describe the bug**
Can't shake the baby Maneater when BetterEmotes is installed

**To Reproduce**
1. Find a baby maneater
2. left click to shake it
3. See it doesnt shake

**Expected behavior**
Baby maneater should shake when held and pressing left click

**Comment by KlutzyBubbles** [comment]
Should be fixed in v.1.5.4, feel free to make a new issue if its still broken.
