### ISSUE TITLE
Incompatibility with ReservedFlashlightSlot and ReservedWalkieSlot

### ISSUE THREAD

**Issue by Hazard15301** [KlutzyBubbles/lc-better-emotes#9]
When using BetterEmotes v1.2.2 and up with the two mods listed above, picking up a walkie or flashlight automatically puts the item into the #3 inventory slot. You can't switch to the flashlight or walkie, it's locked out as if its using the two reserved slots. Disabling this mod returns the ReservedSlot mods to normal functionality. Probably not an issue with the mod, but they are incompatible at this time, nonetheless. If I roll back to v1.2.1 or lower, everything works fine together.

**Comment by KlutzyBubbles** [comment]
> When using BetterEmotes v1.2.2 and up with the two mods listed above, picking up a walkie or flashlight automatically puts the item into the #3 inventory slot. You can't switch to the flashlight or walkie, it's locked out as if its using the two reserved slots. Disabling this mod returns the ReservedSlot mods to normal functionality. Probably not an issue with the mod, but they are incompatible at this time, nonetheless. If I roll back to v1.2.1 or lower, everything works fine together.

I will look into this soon (quite busy the next few days because of Christmas and all). Are you able to give me the full mod list you were using or can you confirm that this still happens with only the Reserved slot mods and this mod.

Just want to eliminate the possibility of another mod that could be aiding in the cause.

**Comment by Hazard15301** [comment]
BepinExPack v5.4.2100
MoreSuits v1.4.1
LC_API v3.0.1
LineCompass v1.0.1
EladsHUD v1.1.0
BiggerBattery v1.0.2
SuitSaver v1.1.2
Doms_Basic_Suit_Colors v1.4.4
LetMeLookDown v1.0.1
LC_DOOM v1.1.2
LethalCompany_InputUtils v0.4.3
Lethal_Company_Enhancer v0.1.8
ShipLoot v1.0.0
ReservedItemSlotCore v1.5.2
ReservedFlashlightSlot v1.4.6
ReservedWalkieSlot v1.4.6
BetterEmotes v1.2.1

Profile code: 018c9467-6eb0-c51e-8799-b9aa92352201

To test I disabled everything but your mod and the Reserved mods. Used the latest version of yours, issue exists. Backtracked through versions until 1.2.1, and Reserved functions as expected. Enabled all mods again, everything still works.

**Comment by KlutzyBubbles** [comment]
> BepinExPack v5.4.2100 MoreSuits v1.4.1 LC_API v3.0.1 LineCompass v1.0.1 EladsHUD v1.1.0 BiggerBattery v1.0.2 SuitSaver v1.1.2 Doms_Basic_Suit_Colors v1.4.4 LetMeLookDown v1.0.1 LC_DOOM v1.1.2 LethalCompany_InputUtils v0.4.3 Lethal_Company_Enhancer v0.1.8 ShipLoot v1.0.0 ReservedItemSlotCore v1.5.2 ReservedFlashlightSlot v1.4.6 ReservedWalkieSlot v1.4.6 BetterEmotes v1.2.1
> 
> Profile code: 018c9467-6eb0-c51e-8799-b9aa92352201
> 
> To test I disabled everything but your mod and the Reserved mods. Used the latest version of yours, issue exists. Backtracked through versions until 1.2.1, and Reserved functions as expected. Enabled all mods again, everything still works.

I wont have a computer to test with for a couple of weeks. I saw the reserved item mods got updated half an hour ago. The changelogs dont indicate that anything would have changed with this issue but might be good to check.

One more question, when you were testing this issue, did it occur on v1.2.0 and v1.2.2? or only v1.2.2 and up.

**Comment by Hazard15301** [comment]
I just tested it, 1.2.0 works fine also. Also tested again with everything updated as of today, issue is still present.

**Comment by Hazard15301** [comment]
I just updated all of my mods, including yours. As of now everything is fixed, so it looks like it was some sort of issue with one of the other mods on that list.
